media: static/img
content:
  - name: docs
    label: Help Docs
    icon: notebook-pen
    path: 'docs'
    type: collection
    subfolders: true
    filename: "{fields.sidebar_position}-{fields.title}.mdx"
    
    view:
      fields: [ title, slug, sidebar_position, id, published ]
      primary: title
      sort: [ title, slug, sidebar_position ]
      default:
        search: ''
        sort: sidebar_position
        order: asc
      
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
        width: half
        
      - name: sidebar_position
        label: Sidebar Position
        type: number
        width: half

      - name: id
        label: ID
        type: string
        default: {fields.title}
        width: half
                
      - name: slug
        label: Slug
        type: string
        required: true
        width: half
        
      - name: title
        label: Title
        type: string
        required: true
        width: full
        
      - name: description
        label: Description
        type: string
        required: false
        width: half
        
      - name: body
        label: Body
        type: rich-text
        required: true
        width: full
        
  - name: sidebar_ts
    label: SidebarConfig2
    path: sidebars.ts
    type: file
    
  - name: sidebar_config
    label: Sidebar Config
    path: _sidebarConfig.yml
    type: file
    
  - name: config
    label: Site Config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
        