import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  userGuideSidebar: [{type: 'autogenerated', dirName: '.'}],
  // adminUserGuideSidebar: [{type: 'autogenerated', dirName: './adminGuide'}]
}

export default sidebars