const defaultTheme = require("tailwindcss/defaultTheme");
const plugin = require("tailwindcss/plugin");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./docs/**/*.{md,mdx,tsx}",
    "./tutorial/**/*.{md,mdx,tsx}",
  ],
  jit: true,
  theme: {
    extend: {
      zIndex: {
        popover: 9,
        modal: 100,
        mobileNavbar: 1000,
        "top-announcement": 1000,
      },
      colors: {
        refine: {
          red: "#FF4C4D",
          orange: "#FF9933",
          yellow: "#FFBF00",
          green: "#1FAD66",
          "green-alt": "#26D97F",
          "tutorial-green": "#24A866",
          cyan: "#0F8A8A",
          "cyan-alt": "#47EBEB",
          blue: "#0080FF",
          selection: "#6EF7F7",
          "blue-alt": "#6EB3F7",
          "blue-2": "#58AFDF",
          "blue-2-light": "#E6F7FF",
          "react-dark-link": "#149ECA",
          "react-light-link": "#087EA4",
          "react-dark-code": "#16181D",
          "react-light-code": "#FFFFFF",
          indigo: "#3333FF",
          "indigo-alt": "#8080FF",
          purple: "#8000FF",
          "purple-alt": "#B366FF",
          pink: "#ED5EC9",
          bg: "#0A0A29",
          kdb: "#DBDBF0",
          "react-dark-orange": "#DB7D27",
          "react-dark-purple": "#8891EC",
          "react-dark-green": "#44AC99",
          "react-dark-green-alt": "#26D97F",
          "react-light-orange": "#C76A15",
          "react-light-purple": "#575FB7",
          "react-light-green": "#2B6E62",
          "react-light-green-alt": "#24A866",
          "react-light-orange-bg": "#FEF5E7",
          "react-light-purple-bg": "#F3F4FD",
          "react-light-green-bg": "#F4FBF9",
          "tutorial-dark-bg": "#1D2026",
          "bg-alt": "#262640",
          "link-dark": "#6EB3F7",
          "link-light": "#0080FF",
          "react-1": "#F6F7F9",
          "react-2": "#EAEBEF",
          "react-3": "#E3E4E5",
          "react-4": "#99A1B3",
          "react-5": "#667084",
          "react-6": "#444955",
          "react-7": "#343A46",
          "react-8": "#23272F",
        },
        gray: {
          0: "rgb(var(--color-gray-0) / <alpha-value>)",
          50: "rgb(var(--color-gray-50) / <alpha-value>)",
          100: "rgb(var(--color-gray-100) / <alpha-value>)",
          200: "rgb(var(--color-gray-200) / <alpha-value>)",
          300: "rgb(var(--color-gray-300) / <alpha-value>)",
          400: "rgb(var(--color-gray-400) / <alpha-value>)",
          500: "rgb(var(--color-gray-500) / <alpha-value>)",
          600: "rgb(var(--color-gray-600) / <alpha-value>)",
          700: "rgb(var(--color-gray-700) / <alpha-value>)",
          800: "rgb(var(--color-gray-800) / <alpha-value>)",
          900: "rgb(var(--color-gray-900) / <alpha-value>)",
          1000: "rgb(var(--color-gray-1000) / <alpha-value>)",
        },

        },
      },
      fontFamily: {
        sans: ["var(--primary-font-sans)", ...defaultTheme.fontFamily.sans],
        mono: ["Source Code Pro", ...defaultTheme.fontFamily.mono],
        montserrat: ["Montserrat", ...defaultTheme.fontFamily.serif],
        disket: ["Disket Mono", ...defaultTheme.fontFamily.mono],
        inter: ["Inter", ...defaultTheme.fontFamily.serif],
        "jetBrains-mono": ["JetBrains Mono", ...defaultTheme.fontFamily.mono],
      },
      dropShadow: {
        "showcase-highlight": [
          "0px 3px 7px rgba(108, 119, 147, 0.141)",

          "0px 13px 13px rgba(108, 119, 147, 0.141)",

          "0px 20px 18px rgba(108, 119, 147, 0.18)",

          "0px 34px 21px rgba(108, 119, 147, 0.2)",
          "0px 54px 23px rgba(108, 119, 147, 0)",
        ],
      },
      boxShadow: {
        modal: "4px 8px 16px rgba(42, 42, 66, 0.25)",
        tile: "6px 8px 16px 0 rgba(42, 42, 66, 0.4)",
        integrationTile: "3px 4px 8px 0 rgba(42, 42, 66, 0.25)",
        tagTile: "3px -2px 8px 0 rgba(42, 42, 66, 0.25)",
        startTiles: "4px 8px 16px rgba(42, 42, 66, 0.25)",
        menuItem: "2px 4px 8px rgba(36, 36, 54, 0.2)",
        "menu-dark": "0px 0px 0px 4px rgba(48, 52, 80, 0.25)",
        "menu-light": "0px 0px 0px 4px rgba(222, 229, 237, 0.25)",
      backgroundColor: {
        "landing-header-bg": "rgba(10, 10, 41, 0.70)",
        "landing-header-border": "rgba(48, 52, 80, 0.70)",
        "common-header-bg-dark": "rgba(29, 30, 48, 0.70)",
        "common-header-bg-light": "rgba(244, 248, 251, 0.85)",
      },
      backdropBlur: {
        "header-blur": "12px",
      },
    screens: {
      ...defaultTheme.screens,
      "content-sm": "480px",
      "widening-start": "544px",
      "content-md": "656px",
      "content-xm": "768px",
      "content-xl": "792px",
      "content-xl-safe": "1376px",
      "content-2xl": "864px",
      "content-4xl": "1536px",
      "header-sm": "640px",
      "header-md": "1200px",
      "doc-form-lg": "824px",
      "doc-form-md": "688px",
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    plugin(({ addVariant }) => {
      addVariant("light", `[data-theme="light"] &`);
    }),
  ],
  corePlugins: {
    // preflight: false,
  },
  }
}