backend:
  name: github
  branch: main 
  repo: CBHFinance/arfHelpDocs


# These lines should *not* be indented
local_backend: true
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: docs
    label: Docs
    label_singular: Doc
    folder: docs
    create: true
    identifier_field: title
    nested:
      depth: 4 
      summary: '{{title}}' 
    fields:
      - label: Sidebar position
        name: sidebar_position
        widget: number
      - label: Title
        name: title
        widget: string
      - label: slug
        name: slug
        widget: string
      - label: Description
        name: description
        required: false
      - label: Body
        name: body
        widget: markdown

    sortable_fields: ["title", "sidebar_position"]
    extension: md
    format: frontmatter
    editor:
      preview: false
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }  

  # - name: categories
  #   label: Categories
  #   label_singular: Category
  #   files:
  #     - 


  # - name: sidebar
  #   label: sidebar
  #   folder: 
  #   identifier_field: 